from pathlib import Path
import json,re,html,shutil
ROOT=Path(__file__).resolve().parent
OUT=ROOT.parent/'outputs'/'health-ai-website'
if (ROOT/'content.json').exists(): D=json.loads((ROOT/'content.json').read_text(encoding='utf8'))
else: D=json.loads((ROOT/'content-data.json').read_text(encoding='utf8')); OUT=ROOT
E=html.escape
routes={'/home':'index.html','/':'index.html','/publication':'publications.html','/people':'people.html','/talk':'service.html#talks','/review':'service.html#reviewing','/honours-and-awards':'awards.html','/association-and-administration':'service.html','/association-and-administration/organization':'service.html#events'}
def url(s):
    s=s.replace('https://ieeexplore-ieee-org.manchester.idm.oclc.org','https://ieeexplore.ieee.org')
    if s.startswith('/'): return routes.get(s,'https://www.hongpengzhou.com'+s)
    return s
def rich(b):
    s=E(b['text'])
    for a in sorted(b['links'],key=lambda a:-len(a['text'])):
        if a['text']: s=s.replace(E(a['text']),f'<a href="{E(url(a["url"]),quote=True)}">{E(a["text"])}</a>',1)
    return s
def para(b):return '<p>'+rich(b)+'</p>'
def ul(bs):return '<ul class="entries">'+''.join('<li>'+rich(b)+'</li>' for b in bs)+'</ul>'
NAV=[('index.html','About'),('publications.html','Publications'),('lab.html','Health AI Lab'),('people.html','People'),('join.html','Join us'),('service.html','Service'),('awards.html','Awards')]
scholar='https://scholar.google.com/citations?user=StuUN6wAAAAJ&hl=en'
email='hongpeng.zhou@manchester.ac.uk'
def side(lab=False):
    if lab:
        return '''<aside class="profile lab-profile"><a class="lab-monogram" href="lab.html" aria-label="Health AI Lab home">H<span>AI</span></a><h2>Health AI Lab</h2><p class="role">AI for biomedical discovery</p><p class="location">Department of Computer Science<br>The University of Manchester<br>Manchester, United Kingdom</p><nav class="lab-menu" aria-label="Lab navigation"><a href="lab.html">Overview</a><a href="people.html">Our people</a><a href="publications.html">Publications</a><a href="news.html">Lab news</a><a href="join.html">Join the lab</a></nav><a class="profile-back" href="index.html">Hongpeng Zhou · Group lead</a></aside>'''
    return f'''<aside class="profile"><img class="portrait" src="portrait.jpg" alt="Hongpeng Zhou" width="190" height="190"><h2>Hongpeng Zhou</h2><p class="role">Dame Kathleen Ollerenshaw Fellow<br>Assistant Professor</p><p class="location">Computer Science<br>The University of Manchester<br>Manchester, United Kingdom</p><div class="profile-links"><a href="mailto:{email}">Email</a><a href="{E(scholar)}">Google Scholar</a><a href="https://github.com/hongpengzhou56">GitHub</a><a href="https://www.linkedin.com/in/hongpeng-zhou-302992130/">LinkedIn</a><a href="https://orcid.org/0000-0002-3894-0116">ORCID</a><a href="https://www.researchgate.net/profile/Zhou-Hongpeng-3">ResearchGate</a><a href="https://u.wechat.com/kKMdf4czhGB-gznAy5jOHSg">WeChat</a></div><a class="lab-link" href="lab.html">Health AI Lab <span aria-hidden="true">↗</span></a></aside>'''
def page(file,title,body,lab=False,description=None):
    desc=description or 'Hongpeng Zhou, Dame Kathleen Ollerenshaw Fellow at The University of Manchester. Machine learning, Bayesian learning, interpretable AI and bioinformatics.'
    nav=''.join(f'<a href="{f}"'+(' aria-current="page"' if f==file else '')+f'>{t}</a>' for f,t in NAV)
    text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)} | Hongpeng Zhou</title><meta name="description" content="{E(desc)}"><meta name="theme-color" content="#4e357a"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"></head><body><a class="skip-link" href="#main">Skip to main content</a><header><div class="header-inner"><a class="brand" href="index.html">Hongpeng Zhou<span>University of Manchester</span></a><nav aria-label="Main navigation">{nav}</nav></div></header><div class="layout">{side(lab)}<main id="main"><div class="eyebrow">{'HEALTH AI LAB' if lab else 'RESEARCH · MANCHESTER'}</div><h1>{E(title)}</h1>{body}</main></div><footer><div>© 2026 Hongpeng Zhou <span>·</span> Health AI Lab</div><div><a href="mailto:{email}">Contact</a><a href="https://github.com/hongpengzhou56/hongpengzhou56.github.io">GitHub</a><a href="https://www.hongpengzhou.com/">Original website</a></div></footer></body></html>'''
    (OUT/file).write_text(text,encoding='utf8')
def news(bs):
    out='<div class="news-list">'
    for b in bs:
        m=re.match(r'\[([^\]]+)\]:?\s*(.*)',b['text'])
        if not m:continue
        date=m[1].replace('-',' '); date=re.sub(r'\b(\d{2})$',r'20\1',date).replace('July','Jul')
        c=dict(b,text=m[2]); out+=f'<article class="news-item"><div class="news-date">{E(date)}</div><div>{rich(c)}</div></article>'
    return out+'</div>'
home='''<p class="intro">I am a <a href="https://research.manchester.ac.uk/en/persons/hongpeng-zhou/">Dame Kathleen Ollerenshaw Fellow</a> (Assistant Professor) in the Department of Computer Science at <a href="https://www.manchester.ac.uk/">The University of Manchester</a>.</p><p>I lead <a href="lab.html">Health AI Lab</a>, where we develop interpretable, efficient and practically useful AI methods for biomedical research. Our aim is to uncover the biological mechanisms behind complex biomedical data and help translate machine learning into biomedical discovery.</p><p>My research interests include <strong>machine learning, sparse Bayesian learning, interpretable learning and bioinformatics</strong>.</p><div class="quick-links"><a href="https://research.manchester.ac.uk/en/persons/hongpeng-zhou/">University profile</a><a href="lab.html">Our research group</a><a href="people.html">Group members</a></div><div class="notice"><strong>Interested in joining us?</strong><p>We welcome enquiries from prospective PhD students, postdoctoral researchers and visiting PhD students.</p><a href="join.html">Explore opportunities</a><a href="https://forms.gle/Lb5VEhT4vzHMJL1q6">PhD enquiry form ↗</a></div><div class="section-heading"><h2>Recent news</h2><a href="news.html">All news</a></div>'''+news(D['home'][12:18])+'''<h2>Background</h2><div class="timeline"><article><div class="period">2021 – 2023</div><h3>Postdoctoral Research Associate · University of Manchester</h3>'''+para(D['home'][39])+'''</article><article><div class="period">2018 – 2022</div><h3>PhD · Delft University of Technology</h3>'''+para(D['home'][41])+'''</article><article><div class="period">2011 – 2017</div><h3>Bachelor’s &amp; Master’s · Harbin Institute of Technology</h3>'''+para(D['home'][43])+'''</article></div>'''
page('index.html','Short bio',home)
page('news.html','News', '<p class="lede">Research, people and updates from our group.</p><h2>2026</h2>'+news(D['home'][12:22])+'<h2>2025</h2>'+news(D['home'][22:37])+'<h2>2024 & earlier</h2><p class="muted">Archived announcements; recruitment and funding calls may have closed.</p>'+news(D['home'][45:]))
lab='''<p class="intro">Interpretable and efficient AI for biomedical discovery.</p><p>Health AI Lab is led by <a href="index.html">Dr Hongpeng Zhou</a> in the Department of Computer Science at The University of Manchester. We develop machine learning methods to understand complex biomedical data and the biological mechanisms they reveal.</p><h2>Research directions</h2><div class="research-list"><article><span class="number">01</span><div><h3>Machine learning for biomedicine</h3><p>AI methods for single-cell transcriptomics, spatial omics and imaging mass cytometry, including foundation models and batch effect correction.</p></div></article><article><span class="number">02</span><div><h3>Interpretable &amp; Bayesian learning</h3><p>Sparse Bayesian methods, interpretable neural networks and learning approaches that reveal structure and mechanisms in data.</p></div></article><article><span class="number">03</span><div><h3>Efficient learning &amp; dynamical systems</h3><p>Neural architecture search, network compression and system identification, connecting machine learning with scientific and engineering applications.</p></div></article></div><h2>Our people</h2><p>Our group brings together postdoctoral researchers, PhD students and collaborators working across machine learning, biomedical science and engineering.</p><div class="quick-links"><a href="people.html">Meet the group</a><a href="publications.html">Read our publications</a></div><div class="notice"><strong>Join Health AI Lab</strong><p>Interested in developing AI methods for fundamental biomedical research challenges?</p><a href="join.html">Opportunities &amp; enquiries</a></div><div class="section-heading"><h2>Latest from the lab</h2><a href="news.html">All news</a></div>'''+news(D['home'][12:16])
page('lab.html','Health AI Lab',lab,True,'Health AI Lab at The University of Manchester, led by Hongpeng Zhou. Interpretable and efficient AI for biomedical discovery.')
def members(bs):
    out='<div class="member-list">'
    for b in bs:
        name,_,detail=b['text'].partition(',')
        if name=='Man Hou Lee':continue
        name=name.replace('ManHou Lee','Man Hou Lee')
        name_html=E(name)
        for a in b['links']:
            if a['text'].strip()==name: name_html=f'<a href="{E(url(a["url"]))}">{E(name)}</a>'
        out+='<article><h3>'+name_html+'</h3><p>'+rich(dict(b,text=detail.strip()))+'</p></article>'
    return out+'</div>'
p=D['people']
people='<p class="lede">Our research group at The University of Manchester.</p><h2>Group lead</h2><div class="lead"><img src="portrait.jpg" width="90" height="90" alt="Hongpeng Zhou"><div><h3><a href="index.html">Dr Hongpeng Zhou</a></h3><p>Dame Kathleen Ollerenshaw Fellow · Assistant Professor</p></div></div><h2>Postdoctoral researchers</h2>'+members(p[27:29])+'<h2>PhD students</h2>'+members(p[30:40])+'<h2>Alumni</h2><h3>Visiting PhD students · Manchester</h3>'+members(p[42:43])+'<h3>Master’s students · Manchester</h3>'+members(p[44:46])+'<h3>Master’s students · TU Delft</h3>'+members(p[47:])
page('people.html','People',people,True)
join='''<p class="intro">Work with us on machine learning for healthcare and biomedical discovery.</p><p>We welcome enquiries from motivated prospective PhD students, postdoctoral researchers and visiting PhD students with a background in machine learning, control science, mathematics, bioinformatics, healthcare or related fields.</p><div class="notice"><strong>Start a conversation</strong><p>For PhD enquiries, please complete the application enquiry form. You are also welcome to contact Hongpeng directly about research fit and potential opportunities.</p><a class="button" href="https://forms.gle/Lb5VEhT4vzHMJL1q6">PhD enquiry form ↗</a><a href="mailto:hongpeng.zhou@manchester.ac.uk">Email Hongpeng</a></div><h2>PhD funding &amp; applications</h2><p>Funding schemes have their own eligibility requirements and deadlines. Check the scheme’s current call and contact us to discuss project availability. Self-funded and part-time PhD enquiries are also welcome.</p>'''+ul(p[18:24])+para(p[24])+'''<h2>Postdoctoral enquiries</h2><p>Please contact us to discuss a potential project and suitable fellowship routes. The following schemes were listed on our group’s website; current calls and eligibility should be checked with each funder.</p>'''+ul(p[4:9])+'''<details><summary>Previous funded PhD opportunities · 2023–2025</summary><p class="muted">Historical project announcements, retained for reference. These are not a list of currently open positions.</p>'''+ul(p[11:18])+'</details>'
page('join.html','Join us',join,True)
pubs=f'<p class="lede">Research in machine learning, biomedicine and dynamical systems.</p><p>See <a href="{E(scholar)}">Google Scholar</a> for the complete and latest publication record.</p><h2>Recent research · 2025–2026</h2>'
recent=[('Foundation Models in Omics Research: A Comprehensive Survey','Briefings in Bioinformatics · Accepted, July 2026',''),('Towards embodied AI in manufacturing: Review, Evaluation, and Future directions','Robotics and Computer-Integrated Manufacturing · 2026',''),('Will predictive AI make discovery research in metabolism obsolete?','npj Metabolic Health and Disease · 2026',''),('Benchmarking a Spatial-Aware Foundation Model: An Empirical Evaluation of CellPLM in Transcriptomics','CIBB 2026 · Oral presentation accepted',''),('Domain-adaptive nonlinear probabilistic latent variable model for vibration-based structural damage detection under climate change','Structural Health Monitoring · 2026',''),('Cross-Scale Contrastive Learning with Subgraph and Line-Graph Views for link prediction','Physica A: Statistical Mechanics and its Applications · 2026',''),('Improved Extended Kalman Filter-Based Disturbance Observers for Exoskeletons','IEEE Transactions on Industrial Electronics · Accepted, February 2026',''),('Rethinking RoPE: A Mathematical Blueprint for N-dimensional Positional Encoding','arXiv preprint · 2025','https://arxiv.org/abs/2504.06308'),('BioBatchNet: A Dual-Encoder Framework for Robust Batch Effect Correction in Imaging Mass Cytometry','bioRxiv preprint · 2025','https://www.biorxiv.org/content/10.1101/2025.03.15.643447v1'),('Machine learning-guided process optimization and comprehensive evaluation of additively manufactured biodegradable Zn-2Cu alloy','Journal of Materials Science and Technology · 2025','https://www.sciencedirect.com/science/article/pii/S1005030225003263'),('ELF autoencoder for unsupervised exploration of flat-band materials using electronic band structure fingerprints','Communications Physics · 2025','https://www.nature.com/articles/s42005-025-01936-2'),('Hierarchical Physics-Informed Neural Network for Rotor System Health Assessment','IEEE Transactions on Automation Science and Engineering · Accepted, January 2025','')]
for title,venue,link in recent:
    pubs+=f'<article class="publication"><h3>{E(title)}</h3><p class="venue">{E(venue)}</p>'+ (f'<a class="paper-link" href="{E(link)}">Paper ↗</a>' if link else '')+'</article>'
pubs+='<h2>Earlier publications</h2>'
for i in range(3,len(D['publication']),2):
    b=D['publication'][i]; links=D['publication'][i+1]['links']
    text=b['text'].replace('Xilin Yina','Xilin Yin').replace('Ken Gavina','Ken Gavin').replace('Pisanòa','Pisanò').replace('Bayesnas: A bayesian','BayesNAS: A Bayesian')
    pubs+='<article class="publication"><p>'+E(text).replace('Hongpeng Zhou','<strong>Hongpeng Zhou</strong>')+'</p><div class="paper-links">'+''.join(f'<a href="{E(url(a["url"]))}">{E(a["text"])} ↗</a>' for a in links)+'</div></article>'
pubs+='<h2>Doctoral thesis</h2><article class="publication"><h3>Bayesian deep learning for system identification</h3><p>Hongpeng Zhou · Delft University of Technology · 2022</p><a href="https://research.tudelft.nl/en/publications/bayesian-deep-learning-for-system-identification">Read thesis ↗</a></article>'
page('publications.html','Publications',pubs)
service='<p class="lede">Talks, academic service and community activities.</p><div class="quick-links"><a href="#talks">Talks</a><a href="#reviewing">Reviewing</a><a href="#community">Community</a><a href="#events">Events</a></div><h2 id="talks">Selected talks</h2>'+ul([D['home'][26],D['home'][27],D['home'][33]])+ul(D['talk'][1:])+'<h2 id="reviewing">Peer review</h2><h3>Journals</h3>'+ul(D['review'][2:19])+'<h3>Conferences</h3>'+ul(D['review'][20:])+'<h2 id="community">Associations &amp; administration</h2>'+ul(D['association-and-administration'][2:6])+ul(D['association-and-administration'][7:])+'<h2 id="events">Past events</h2><h3>Computational &amp; Experimental Spatial Omics</h3><p>4 March 2024 · Michael Smith Building, Manchester</p><p>A one-day workshop bringing together computational and experimental spatial omics methods and creating opportunities for collaboration.</p>'
page('service.html','Talks & academic service',service)
awards='<p class="lede">Fellowships, awards and research support.</p><h2>Recent recognition &amp; support</h2>'+ul([D['home'][18],D['home'][20],D['home'][22],D['home'][23],D['home'][24],D['home'][25],D['home'][31]])+'<h2>Earlier honours &amp; awards</h2>'+ul(D['honours-and-awards'][1:])
awards=awards.replace('fundings supppot','funding support').replace('funding supppot','funding support')
page('awards.html','Honours & awards',awards)
page('404.html','Page not found','<p>The page you are looking for is not here.</p><p><a href="index.html">Return to Hongpeng Zhou’s homepage</a> or explore <a href="lab.html">Health AI Lab</a>.</p>')
(OUT/'content-data.json').write_text(json.dumps(D,ensure_ascii=False,indent=2),encoding='utf8')
(OUT/'.nojekyll').write_text('')
print('Built',len(list(OUT.glob('*.html'))),'pages in',OUT)
